### ISSUE TITLE
Feature Request: Good Job!

### ISSUE THREAD

**Issue by jordanwillis** [Zantolotov/jammming#6]
Your feature request is well written, throughly explains the problem and high level solution, and proposes some nice features that would definitely improve the overall user experience.

Technically, you could argue that you are describing more than a single feature request, most of the items appear to be small enough that combining them into a single feature request is ok.  Be sure to consider the relative size of each feature when following a similar approach on a real live project to make sure you don't end up with more scope than can be handled.

I also noticed that you discussed in the **Technical Design** section that the "enter triggering search" feature would also restore the user's search term upon login, however this aspect of the feature did not seem to be covered in more detail regarding how it could be implemented.  From a feasibility perspective, since we are talking about maintaining state even after the user logs off, then you will probably have to pass the search term to your backend and persistent it in some datastore (such as a database).  You might also want to consider adding a visual mockup of the features that impact the user interface (such as the album pictures and play sample feature).

My other main feedback is your **Caveats** section.  Typically you would use this section to describe potential alternate solutions or key corner cases or situations that you should account for.  Instead, you seem to be using the section to justify the purpose behind each feature request.  I think justification is definitely important because it drives the true importance of the feature, but make sure you also document alternatives / special considerations so that you can use it to drive a good conversation with other stakeholders on the project.

Overall you did a great job authoring this feature request and demonstrated your effective technical and communication skills (which are key to being a contributor to any engineering team).  

Now for some more fun (if you have the time), see if you can implement some of the features based upon all the good work you did documenting them!

**Comment by Zantolotov** [comment]
Thank you for the review. I talked about the restoration of the term searched but I erased it at the last moment because I didn't really know if it worked. I tried to set a logging state in App which can switch when the token is taken after the first search. Then in SearchBar render() I tried to set the search term as a state that need to be set as the value of the input after the logging to be true. Can you help me with an example ? 
Otherwise I had a hard time with the caveats because I totally struggled to get to one Idea to get realised so I didn't have alternative solutions (mea culpa). Thanks again for your help!
